stages:
  - infra
  - triggers

infra:
  stage: infra
  trigger:
    include: infrastructure/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
      - infrastructure/*
    
backend:
 stage: triggers
 trigger:
   include: backend/.gitlab-ci.yml
   strategy: depend
 rules:
   - changes:
       - backend/*

frontend:
  stage: triggers
  trigger:
    include: frontend/.gitlab-ci.yml
    strategy: depend
  needs: ["backend"]
  rules:
    - changes:
        - frontend/*